package org.cxvsinergy.webjdbc;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

public abstract class AbstractProxyConnection implements java.sql.Connection
{
	

	public AbstractProxyConnection()	
	{}
	
	
	protected abstract Connection getImpl();
	
	public void abort(Executor executor) throws SQLException {
		getImpl().abort(executor);
	}

	public void clearWarnings() throws SQLException {
		getImpl().clearWarnings();
	}

	public void close() throws SQLException {
		getImpl().close();
	}

	public void commit() throws SQLException {
		getImpl().commit();
	}

	public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
		return getImpl().createArrayOf(typeName, elements);
	}

	public Blob createBlob() throws SQLException {
		return getImpl().createBlob();
	}

	public Clob createClob() throws SQLException {
		return getImpl().createClob();
	}

	public NClob createNClob() throws SQLException {
		return getImpl().createNClob();
	}

	public SQLXML createSQLXML() throws SQLException {
		return getImpl().createSQLXML();
	}

	public Statement createStatement() throws SQLException {
		return getImpl().createStatement();
	}

	public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability)
			throws SQLException {
		return getImpl().createStatement(resultSetType, resultSetConcurrency, resultSetHoldability);
	}

	public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
		return getImpl().createStatement(resultSetType, resultSetConcurrency);
	}

	public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
		return getImpl().createStruct(typeName, attributes);
	}

	public boolean getAutoCommit() throws SQLException {
		return getImpl().getAutoCommit();
	}

	public String getCatalog() throws SQLException {
		return getImpl().getCatalog();
	}

	public Properties getClientInfo() throws SQLException {
		return getImpl().getClientInfo();
	}

	public String getClientInfo(String name) throws SQLException {
		return getImpl().getClientInfo(name);
	}

	public int getHoldability() throws SQLException {
		return getImpl().getHoldability();
	}

	public DatabaseMetaData getMetaData() throws SQLException {
		return getImpl().getMetaData();
	}

	public int getNetworkTimeout() throws SQLException {
		return getImpl().getNetworkTimeout();
	}

	public String getSchema() throws SQLException {
		return getImpl().getSchema();
	}

	public int getTransactionIsolation() throws SQLException {
		return getImpl().getTransactionIsolation();
	}

	public Map<String, Class<?>> getTypeMap() throws SQLException {
		return getImpl().getTypeMap();
	}

	public SQLWarning getWarnings() throws SQLException {
		return getImpl().getWarnings();
	}

	public boolean isClosed() throws SQLException {
		return getImpl().isClosed();
	}

	public boolean isReadOnly() throws SQLException {
		return getImpl().isReadOnly();
	}

	public boolean isValid(int timeout) throws SQLException {
		return getImpl().isValid(timeout);
	}

	public boolean isWrapperFor(Class<?> arg0) throws SQLException {
		return getImpl().isWrapperFor(arg0);
	}

	public String nativeSQL(String sql) throws SQLException {
		return getImpl().nativeSQL(sql);
	}

	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency,
			int resultSetHoldability) throws SQLException {
		return getImpl().prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
	}

	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		return getImpl().prepareCall(sql, resultSetType, resultSetConcurrency);
	}

	public CallableStatement prepareCall(String sql) throws SQLException {
		return getImpl().prepareCall(sql);
	}

	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency,
			int resultSetHoldability) throws SQLException {
		return getImpl().prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
	}

	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
			throws SQLException {
		return getImpl().prepareStatement(sql, resultSetType, resultSetConcurrency);
	}

	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
		return getImpl().prepareStatement(sql, autoGeneratedKeys);
	}

	public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
		return getImpl().prepareStatement(sql, columnIndexes);
	}

	public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
		return getImpl().prepareStatement(sql, columnNames);
	}

	public PreparedStatement prepareStatement(String sql) throws SQLException {
		return getImpl().prepareStatement(sql);
	}

	public void releaseSavepoint(Savepoint savepoint) throws SQLException {
		getImpl().releaseSavepoint(savepoint);
	}

	public void rollback() throws SQLException {
		getImpl().rollback();
	}

	public void rollback(Savepoint savepoint) throws SQLException {
		getImpl().rollback(savepoint);
	}

	public void setAutoCommit(boolean autoCommit) throws SQLException {
		getImpl().setAutoCommit(autoCommit);
	}

	public void setCatalog(String catalog) throws SQLException {
		getImpl().setCatalog(catalog);
	}

	public void setClientInfo(Properties properties) throws SQLClientInfoException {
		getImpl().setClientInfo(properties);
	}

	public void setClientInfo(String name, String value) throws SQLClientInfoException {
		getImpl().setClientInfo(name, value);
	}

	public void setHoldability(int holdability) throws SQLException {
		getImpl().setHoldability(holdability);
	}

	public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
		getImpl().setNetworkTimeout(executor, milliseconds);
	}

	public void setReadOnly(boolean readOnly) throws SQLException {
		getImpl().setReadOnly(readOnly);
	}

	public Savepoint setSavepoint() throws SQLException {
		return getImpl().setSavepoint();
	}

	public Savepoint setSavepoint(String name) throws SQLException {
		return getImpl().setSavepoint(name);
	}

	public void setSchema(String schema) throws SQLException {
		getImpl().setSchema(schema);
	}

	public void setTransactionIsolation(int level) throws SQLException {
		getImpl().setTransactionIsolation(level);
	}

	public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
		getImpl().setTypeMap(map);
	}

	public <T> T unwrap(Class<T> arg0) throws SQLException {
		return getImpl().unwrap(arg0);
	}
	
		

}
